#!/usr/bin/env node
"use strict"

var stdEsm= require( "@std/esm")( module)
exports.webMidiNanoKontrol= stdEsm( "./web-midi-nanokontrol.js").default
exports.main= stdEsm( "./main.js")
exports.messages= stdEsm( "./messages.js")
exports.scene= stdEsm( "./scene.js")

exports.webMidiMessage= stdEsm( "web-midi-message")
exports.webMidiApi= stdEsm( "web-midi-api")

if( require.main=== module){
	module.exports.main()
}
