#!/usr/bin/env node
"use strict"

var stdEsm= require( "@std/esm")( module)
exports.webMidiNanoKontrol= stdEsm( "./web-midi-nanokontrol.js").default
exports.main= stdEsm( "./main.js").default
exports.messages= stdEsm( "./messages.js").default

if( require.main=== module){
	module.exports.main()
}
