#!/usr/bin/env node
"use strict"

var stdEsm= require("@std/esm")(module, options)
module.exports= stdEsm("./web-midi-nanokontrol.js").default
module.exports.main= stdEsm("./main.js").default

if( require.main=== module){
	module.exports.main()
}
